/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 -k public/models/Foot.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Foot.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh name="Foot" geometry={nodes.Foot.geometry} material={materials.FootDetails} position={[0.01, 2.573, 0.818]} rotation={[0, 0, -0.087]} scale={[-26.149, -26.149, -39.979]} />
      <mesh name="Toe5" geometry={nodes.Toe5.geometry} material={materials.FootDetails} position={[0.01, 2.573, 0.818]} rotation={[0, 0, -0.087]} scale={[-26.149, -26.149, -39.979]} />
      <mesh name="Toe1" geometry={nodes.Toe1.geometry} material={materials.FootDetails} position={[0.01, 2.573, 0.818]} rotation={[0, 0, -0.087]} scale={[-26.149, -26.149, -39.979]} />
      <mesh name="Toe2" geometry={nodes.Toe2.geometry} material={materials.FootDetails} position={[0.01, 2.573, 0.818]} rotation={[0, 0, -0.087]} scale={[-26.149, -26.149, -39.979]} />
      <mesh name="Toe3" geometry={nodes.Toe3.geometry} material={materials.FootDetails} position={[0.01, 2.573, 0.818]} rotation={[0, 0, -0.087]} scale={[-26.149, -26.149, -39.979]} />
      <mesh name="Toe4" geometry={nodes.Toe4.geometry} material={materials.FootDetails} position={[0.01, 2.573, 0.818]} rotation={[0, 0, -0.087]} scale={[-26.149, -26.149, -39.979]} />
    </group>
  )
}

useGLTF.preload('/Foot.gltf')
