/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 -k public/models/FriesBox.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/FriesBox.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh name="FriesPaperBox" geometry={nodes.FriesPaperBox.geometry} material={materials.BoxLogo} rotation={[Math.PI / 2, 0, 0]} scale={0.183} />
    </group>
  )
}

useGLTF.preload('/FriesBox.gltf')
